### PR TITLE
Add support for Custom Header background color scheme

### PR DESCRIPTION
**Pull request by tiagofreire-pt**
Needs also another line for configure the lovelace.yaml:

```yaml
custom_header:
  background: var(--ch-background)
```

### CODE REVIEW

**Comment by basnijholt** [comment]
Thanks! What does this do exactly?

Can you maybe post a screenshot?

**Comment by tiagofreire-pt** [comment]
> Thanks! What does this do exactly?
> 
> Can you maybe post a screenshot?

It does the same thing of posting the rgba() configuration inside the lovelace.yaml file, but this way the lovelace.yaml has always the same code for different themes applied. Just defines another var for setting the header background color scheme from the theme yaml file.

**Comment by tiagofreire-pt** [comment]
Just for reference: https://maykar.github.io/custom-header/#styling/advanced

**Comment by simposiummm** [comment]
can you confirm if this will be implemented?

**Comment by basnijholt** [comment]
No, custom_header is deprecated.

**Pull request closed without merging**
