### PR TITLE
Add paper-item-icon-active-color

### PR DESCRIPTION
**Pull request by fantomnotabene**
Which applies to icon when e.g. in glance card, binary_sensor is 'on'.

### CODE REVIEW

**Comment by fantomnotabene** [comment]
Like this
Снимок экрана 2020-03-21 в 10 40 05
which is not working so now

**Comment by basnijholt** [comment]
Great, thanks!

**Comment by basnijholt** [comment]
@fantomnotabene, unfortunately, I had to revert your changes because it caused a problem: https://github.com/basnijholt/lovelace-ios-dark-mode-theme/issues/35

**Comment by lollo78** [comment]
what a pity!
I hope for an inclusive fix

**Comment by pietia7** [comment]
Hi, are your sure that commit from @fantomnotabene was the culprit?
I'm still on version: 9b281bc and can see tokens just fine.

Zrzut ekranu 2020-03-23 o 14 20 06

**Comment by fantomnotabene** [comment]
I think this was a heisenbug. And had nothing to do with my PR. 
But I figured out, that we can just use `state-icon-active-color` with color specified here in the comment https://github.com/basnijholt/lovelace-ios-dark-mode-theme/blob/fff49d091e869618a79f6118b0b4419b713d16a6/themes/ios-dark-mode.yaml#L28
without adding `paper-dialog-background-color` at all
So I'll create a new PR soon, with one more little improvement that will turn
Снимок экрана 2020-03-23 в 15 44 04
into
Снимок экрана 2020-03-23 в 16 10 27
(making `disabled-text-color` a little brighter so that's not so hard to see whats there)

**Pull request merged**
